/**
 * Created by Szane on 17/7/22.
 */
/**
 * Created by ling xue on 2016/3/2.
 */

var moduleInfo = {mch: 'sso', desc: 'login'};
/**
 * USER REQUEST TYPE
 */
var USER_REQUEST_HEAD_CLIENT = "client-id";

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1;
var USER_STATUS_NOT_ACTIVE = 0;

var ADMIN_STATUS_DROP = 0;//已删除
var ADMIN_STATUS_ACTIVE = 1;//在使用

/**
 * SMS SEND TYPE
 */
var SMS_REG_TYPE = 1;
var SMS_PSWD_TYPE = 2;
var SMS_PHONE_TYPE = 3;//修改手机号

/**
 * BIZ TYPE
 * owner-货主 agency-货代 shipping-船公司 truck team-车队
 */
var BIZ_TYPE_OWNER = 1;
var BIZ_TYPE_AGENCY = 2;
var BIZ_TYPE_SHIPPING = 3;
var BIZ_TYPE_TRUCK_TEAM = 4;
/**
 * BIZ STATUS
 */
var BIZ_STATUS_INIT = 0;
var BIZ_STATUS_VERIFIED_NO = 1;
var BIZ_STATUS_FORBIDDEN = 2;
var BIZ_STATUS_VERIFIED = 9;
/**
 * TRUCK TYPE
 * OWNED-自有 EXTERNARL-挂靠
 */
var TRUCK_TYPE_OWNED = 1;
var TRUCK_TYPE_EXTERNAL = 2;

/**
 * TRUCK STATUS
 */
var TRUCK_STATUS_FORBIDDEN = 0;
var TRUCK_STATUS_PENDING = 1;
var TRUCK_STATUS_REJECKED = 2;
var TRUCK_STATUS_PAUSED = 3;
var TRUCK_STATUS_VERIFIED = 9;

var TRUCK_STATUS_ACTIVE = 1;
var TRUCK_STATUS_INACTIVE = 0;
/**
 * BIZ VERIFY STATUS
 */
var BIZ_VERIFY_STATUS_PENDING = 1;
var BIZ_VERIFY_REJECTED = 2;
var BIZ_VERIFY_VERIFIED = 9;

/**
 * DRIVER STATUS
 */

var DRIVER_STATUS_FORBIDDEN = 0;
var DRIVER_STATUS_PENDING = 1;
var DRIVER_STATUS_REJECKED = 2;
var DRIVER_STATUS_PAUSED = 3;
var DRIVER_STATUS_VERIFIED = 9;

var DRIVER_STATUS_ACTIVE = 1;
var DRIVER_STATUS_INACTIVE = 0;

/**
 * VERIFY HISTORY TYPE
 */
var VERIFY_HIS_TYPE_BIZ = 1;
var VERIFY_HIS_TYPE_TRUCK = 2;
var VERIFY_HIS_TYPE_DRIVER = 3;

/**
 *
 */
var VERIFY_HIS_STATUS_SUCCESS = 1;
var VERIFY_HIS_STATUS_FAILED = 0;


/**
 * CAPTCHA TYPE
 */

var EXPIRED_TIME_CAPTCHA = 300;

var EXPIRED_TIME_REG_SMS = 900;

var EXPIRED_TIME_PSWD_SMS = 900;

var EXPIRED_TIME_PHONE_SMS = 900;

var CACHE_APPEND_CPATCHA = "CPA_";

var CACHE_APPEND_REG = "REG_";

var CACHE_APPEND_PSWD = "PWD_";

var CACHE_APPEND_RST = "RST_";

/**
 * OAUTH USER GROUP
 *
 */

var USER_GROUP_NOT_VERIFIED = 'not_verified'; //已注册但未通过验证
var USER_GROUP_OWNER = 'owner'; //货主
var USER_GROUP_AGENCY = 'agency'; //货代
var USER_GROUP_SHIPPING = 'shipping'; //船公司
var USER_GROUP_TRUCK_TEAM = 'truck_team'; //车队
var USER_GROUP_DRIVER = 'driver'; //司机
var USER_GROUP_ADMIN = 'admin'; //后台管理员

var USER_TYPE_NOT_VERIFIED = 0; //已注册但未通过验证
var USER_TYPE_OWNER = 1; //货主
var USER_TYPE_AGENCY = 2; //货代
var USER_TYPE_SHIPPING = 3; //船公司
var USER_TYPE_TRUCK_TEAM = 4; //车队
var USER_TYPE_DRIVER = 5; //司机
var USER_TYPE_ADMIN = 9; //后台管理员
var USER_TYPE_MCH = 11; //系统内部模块

var USER_SUB_TYPE_GUEST = 0;//游客
var USER_SUB_TYPE_NOT_VERIFIED = 1;//已注册但未通过验证
var USER_SUB_TYPE_AGENCY_ADMIN = 2;//货代管理员
var USER_SUB_TYPE_AGENCY_OPERATOR = 3;//货代业务员
var USER_SUB_TYPE_AGENCY_FINANCE = 4;//货代财务
var USER_SUB_TYPE_TRUCK_ADMIN = 5;//车队管理员
var USER_SUB_TYPE_TRUCK_DISPATCH = 6;//车队调度
var USER_SUB_TYPE_TRUCK_FINANCE = 7;//车队财务
var USER_SUB_TYPE_TRUCK_DRIVER = 8;//车队司机


var ADMIN_TYPE_SUPER = 99;//超级管理员
var ADMIN_TYPE_CUSTOMER_SERVICE = 9;//客服
var ADMIN_TYPE_SYSTEM = 10;//系统管理员
var ADMIN_TYPE_CHECK = 11;//审核员
var ADMIN_TYPE_DISPATCH = 12;//平台调度员
var ADMIN_TYPE_PRICE_MANAGEMENT = 13;//运价管理员
var ADMIN_TYPE_FINANCE = 14;//财务操作员
var ADMIN_TYPE_ANALYSIS = 15;//数据观察员


var NOTIFY_STATUS_READED = 2; //已读
var NOTIFY_STATUS_READED_NO = 1; //未读

var BROWSER_IE = 1;
var BROWSER_CHROME = 2;
var BROWSER_FIREFOX = 3;
var BROWSER_SAFARI = 4;
var BROWSER_OTHER = 5;
var APP_ANDROID = 6;
var APP_IOS = 7;
var DEVICE_UNKNOWN = 8;

var SUBSCRIBE_STATUS_ON = 1;
var SUBSCRIBE_STATUS_OFF = 0;

var PRIORITY_DEFAULT = 0;
var PRIORITY_MINOR = 1;
var PRIORITY_PRIME = 2;

var BONUS_GET = 1;
var BONUS_COST = 2;

var BONUS_STATUS_INVALID = 0;//无效的
var BONUS_STATUS_USABLE = 1;//有效的
var BONUS_STATUS_OLD = 2;//过期的

var BONUS_TYPE_AGENT_CREATE_ORDER = 1;//委托陆运
var BONUS_TYPE_AGENT_CONTAINER_ORDER = 2;//委托订箱
var BONUS_TYPE_AGENT_INSURANCE = 3;//委托保险
var BONUS_TYPE_AGENT_SIGN_UP = 4;//注册有礼
var BONUS_TYPE_AGENT_ORDER_ADD = 5;//附加积分
var BONUS_TYPE_AGENT_BREAKING_ORDER = 6;//首单奖励
var BONUS_TYPE_AGENT_RATING = 7;//评价积分

var BONUS_TYPE_DRIVER_ROUTE = 8;//区域奖励
var BONUS_TYPE_DRIVER_ORDER_AMOUNT = 9;//订单数奖励
var BONUS_TYPE_DRIVER_SIGN_UP = 10;//注册有礼
var BONUS_TYPE_DRIVER_BREAKING_ORDER = 11;//首单奖励
var BONUS_TYPE_DRIVER_COMPLAINED = 12;//客户投诉

var BONUS_COST_TYPE_UNBALANCED_PAY = 13;//未出账单抵扣

var BONUS_TYPE_AGENT_CANCEL = 14;//货代取消订单回退积分

module.exports = {
    moduleInfo: moduleInfo,

    PRIORITY_DEFAULT: PRIORITY_DEFAULT,
    PRIORITY_MINOR: PRIORITY_MINOR,
    PRIORITY_PRIME: PRIORITY_PRIME,

    SUBSCRIBE_STATUS_ON: SUBSCRIBE_STATUS_ON,
    SUBSCRIBE_STATUS_OFF: SUBSCRIBE_STATUS_OFF,

    BONUS_TYPE_AGENT_CREATE_ORDER: BONUS_TYPE_AGENT_CREATE_ORDER,
    BONUS_TYPE_AGENT_CONTAINER_ORDER: BONUS_TYPE_AGENT_CONTAINER_ORDER,
    BONUS_TYPE_AGENT_INSURANCE: BONUS_TYPE_AGENT_INSURANCE,
    BONUS_TYPE_AGENT_SIGN_UP: BONUS_TYPE_AGENT_SIGN_UP,
    BONUS_TYPE_AGENT_ORDER_ADD: BONUS_TYPE_AGENT_ORDER_ADD,
    BONUS_TYPE_AGENT_BREAKING_ORDER: BONUS_TYPE_AGENT_BREAKING_ORDER,
    BONUS_TYPE_AGENT_RATING: BONUS_TYPE_AGENT_RATING,
    BONUS_TYPE_DRIVER_ROUTE: BONUS_TYPE_DRIVER_ROUTE,
    BONUS_TYPE_DRIVER_ORDER_AMOUNT: BONUS_TYPE_DRIVER_ORDER_AMOUNT,
    BONUS_TYPE_DRIVER_SIGN_UP: BONUS_TYPE_DRIVER_SIGN_UP,
    BONUS_TYPE_DRIVER_BREAKING_ORDER: BONUS_TYPE_DRIVER_BREAKING_ORDER,
    BONUS_TYPE_DRIVER_COMPLAINED: BONUS_TYPE_DRIVER_COMPLAINED,

    BONUS_COST_TYPE_UNBALANCED_PAY: BONUS_COST_TYPE_UNBALANCED_PAY,
    BONUS_TYPE_AGENT_CANCEL: BONUS_TYPE_AGENT_CANCEL,

    USER_REQUEST_HEAD_CLIENT: USER_REQUEST_HEAD_CLIENT,
    USER_STATUS_ACTIVE: USER_STATUS_ACTIVE,
    USER_STATUS_NOT_ACTIVE: USER_STATUS_NOT_ACTIVE,

    ADMIN_STATUS_DROP: ADMIN_STATUS_DROP,
    ADMIN_STATUS_ACTIVE: ADMIN_STATUS_ACTIVE,

    BROWSER_IE: BROWSER_IE,
    BROWSER_CHROME: BROWSER_CHROME,
    BROWSER_FIREFOX: BROWSER_FIREFOX,
    BROWSER_SAFARI: BROWSER_SAFARI,
    BROWSER_OTHER: BROWSER_OTHER,
    APP_ANDROID: APP_ANDROID,
    APP_IOS: APP_IOS,
    DEVICE_UNKNOWN: DEVICE_UNKNOWN,

    SMS_REG_TYPE: SMS_REG_TYPE,
    SMS_PSWD_TYPE: SMS_PSWD_TYPE,
    SMS_PHONE_TYPE: SMS_PHONE_TYPE,

    BIZ_TYPE_OWNER: BIZ_TYPE_OWNER,
    BIZ_TYPE_AGENCY: BIZ_TYPE_AGENCY,
    BIZ_TYPE_SHIPPING: BIZ_TYPE_SHIPPING,
    BIZ_TYPE_TRUCK_TEAM: BIZ_TYPE_TRUCK_TEAM,
    BIZ_STATUS_INIT: BIZ_STATUS_INIT,
    BIZ_STATUS_FORBIDDEN: BIZ_STATUS_FORBIDDEN,
    BIZ_STATUS_VERIFIED_NO: BIZ_STATUS_VERIFIED_NO,
    BIZ_STATUS_VERIFIED: BIZ_STATUS_VERIFIED,
    TRUCK_TYPE_OWNED: TRUCK_TYPE_OWNED,
    TRUCK_TYPE_EXTERNAL: TRUCK_TYPE_EXTERNAL,
    BIZ_VERIFY_STATUS_PENDING: BIZ_VERIFY_STATUS_PENDING,
    BIZ_VERIFY_REJECTED: BIZ_VERIFY_REJECTED,
    BIZ_VERIFY_VERIFIED: BIZ_VERIFY_VERIFIED,

    TRUCK_STATUS_FORBIDDEN: TRUCK_STATUS_FORBIDDEN,
    TRUCK_STATUS_PENDING: TRUCK_STATUS_PENDING,
    TRUCK_STATUS_REJECKED: TRUCK_STATUS_REJECKED,
    TRUCK_STATUS_PAUSED: TRUCK_STATUS_PAUSED,
    TRUCK_STATUS_VERIFIED: TRUCK_STATUS_VERIFIED,
    DRIVER_STATUS_FORBIDDEN: DRIVER_STATUS_FORBIDDEN,
    DRIVER_STATUS_PENDING: DRIVER_STATUS_PENDING,
    DRIVER_STATUS_REJECKED: DRIVER_STATUS_REJECKED,
    DRIVER_STATUS_PAUSED: DRIVER_STATUS_PAUSED,
    DRIVER_STATUS_VERIFIED: DRIVER_STATUS_VERIFIED,
    DRIVER_STATUS_ACTIVE: DRIVER_STATUS_ACTIVE,
    DRIVER_STATUS_INACTIVE: DRIVER_STATUS_INACTIVE,

    VERIFY_HIS_TYPE_BIZ: VERIFY_HIS_TYPE_BIZ,
    VERIFY_HIS_TYPE_TRUCK: VERIFY_HIS_TYPE_TRUCK,
    VERIFY_HIS_TYPE_DRIVER: VERIFY_HIS_TYPE_DRIVER,
    VERIFY_HIS_STATUS_SUCCESS: VERIFY_HIS_STATUS_SUCCESS,
    VERIFY_HIS_STATUS_FAILED: VERIFY_HIS_STATUS_FAILED,

    EXPIRED_TIME_CAPTCHA: EXPIRED_TIME_CAPTCHA,
    EXPIRED_TIME_REG_SMS: EXPIRED_TIME_REG_SMS,
    EXPIRED_TIME_PSWD_SMS: EXPIRED_TIME_PSWD_SMS,
    EXPIRED_TIME_PHONE_SMS: EXPIRED_TIME_PHONE_SMS,

    CACHE_APPEND_CPATCHA: CACHE_APPEND_CPATCHA,
    CACHE_APPEND_REG: CACHE_APPEND_REG,
    CACHE_APPEND_PSWD: CACHE_APPEND_PSWD,
    CACHE_APPEND_RST: CACHE_APPEND_RST,

    TRUCK_STATUS_ACTIVE: TRUCK_STATUS_ACTIVE,
    TRUCK_STATUS_INACTIVE: TRUCK_STATUS_INACTIVE,

    USER_GROUP_NOT_VERIFIED: USER_GROUP_NOT_VERIFIED,
    USER_GROUP_OWNER: USER_GROUP_OWNER,
    USER_GROUP_AGENCY: USER_GROUP_AGENCY,
    USER_GROUP_SHIPPING: USER_GROUP_SHIPPING,
    USER_GROUP_TRUCK_TEAM: USER_GROUP_TRUCK_TEAM,
    USER_GROUP_DRIVER: USER_GROUP_DRIVER,
    USER_GROUP_ADMIN: USER_GROUP_ADMIN,

    USER_TYPE_NOT_VERIFIED: USER_TYPE_NOT_VERIFIED,
    USER_TYPE_OWNER: USER_TYPE_OWNER,
    USER_TYPE_AGENCY: USER_TYPE_AGENCY,
    USER_TYPE_SHIPPING: USER_TYPE_SHIPPING,
    USER_TYPE_TRUCK_TEAM: USER_TYPE_TRUCK_TEAM,
    USER_TYPE_DRIVER: USER_TYPE_DRIVER,
    USER_TYPE_ADMIN: USER_TYPE_ADMIN,
    USER_TYPE_MCH: USER_TYPE_MCH,

    USER_SUB_TYPE_GUEST: USER_SUB_TYPE_GUEST,
    USER_SUB_TYPE_NOT_VERIFIED: USER_SUB_TYPE_NOT_VERIFIED,
    USER_SUB_TYPE_AGENCY_ADMIN: USER_SUB_TYPE_AGENCY_ADMIN,
    USER_SUB_TYPE_AGENCY_OPERATOR: USER_SUB_TYPE_AGENCY_OPERATOR,
    USER_SUB_TYPE_AGENCY_FINANCE: USER_SUB_TYPE_AGENCY_FINANCE,
    USER_SUB_TYPE_TRUCK_ADMIN: USER_SUB_TYPE_TRUCK_ADMIN,
    USER_SUB_TYPE_TRUCK_DISPATCH: USER_SUB_TYPE_TRUCK_DISPATCH,
    USER_SUB_TYPE_TRUCK_FINANCE: USER_SUB_TYPE_TRUCK_FINANCE,
    USER_SUB_TYPE_TRUCK_DRIVER: USER_SUB_TYPE_TRUCK_DRIVER,

    ADMIN_TYPE_CUSTOMER_SERVICE: ADMIN_TYPE_CUSTOMER_SERVICE,
    ADMIN_TYPE_SYSTEM: ADMIN_TYPE_SYSTEM,
    ADMIN_TYPE_CHECK: ADMIN_TYPE_CHECK,
    ADMIN_TYPE_DISPATCH: ADMIN_TYPE_DISPATCH,
    ADMIN_TYPE_PRICE_MANAGEMENT: ADMIN_TYPE_PRICE_MANAGEMENT,
    ADMIN_TYPE_FINANCE: ADMIN_TYPE_FINANCE,
    ADMIN_TYPE_SUPER: ADMIN_TYPE_SUPER,
    ADMIN_TYPE_ANALYSIS: ADMIN_TYPE_ANALYSIS,

    NOTIFY_STATUS_READED: NOTIFY_STATUS_READED,
    NOTIFY_STATUS_READED_NO: NOTIFY_STATUS_READED_NO
};
