/**
 * Created by Szane on 17/7/22.
 */
module.exports = {
    CUST_SIGNUP_EMAIL_REGISTERED: `该邮箱已被注册`,
    CUST_LOGIN_USER_UNREGISTERED: `用户尚未注册`,
    CUST_ORIGIN_PSWD_ERROR: `登录密码错误`,
    CUST_LOGIN_PSWD_ERROR: `初始密码错误`,
    CUST_ACTIVE_STATE_ERROR: `用户未被激活`,
    CUST_FORBIDDEN_STATE_ERROR: `该用户已被禁用`,
    ACCESS_TOKEN_ERROR: `手机号已被注册`,
    ACCESS_TOKEN_EXPIRED: `短信验证码错误`,
    ACCESS_TOKEN_NOT_ACTIVE: `当前用户验证信息已失效`,
    ACCESS_TOKEN_NOT_MATCH: `当前登录已过期`,
    SYS_INTERNAL_ERROR_MSG: `当前用户尚未激活`,
    SYS_AUTH_TOKEN_ERROR: `当前用户身份不匹配`,
    SYS_MESSAGE_QUEUE_ERROR_MSG: `Web Service Internal Error.`,
    CUST_SIGNUP_PHONE_REGISTERED: `Access token error ,the Api can't be accessed`,
    CUST_SMS_CAPTCHA_ERROR: `Message queue error!`,
    IMG_QUERY_NO_EXIST: `图片不存在`,
    TENANT_NOT_EXIST: `Tenant does not exist`,
    ERROR_PARAMS_EMPTY: "输入内容不能为空",
    ERROR_USER_NAME_ADDED: "此用户名已被注册",
    ERROR_DRIVER_REFER_USED: "邀请码已经被使用,请联系车队管理员",
    ERROR_TRUCKTEAM_ADDED: "该车队已经添加",
    ERROR_USER_VALIDATE: "用户名或密码错误",
    ERROR_TRUCK_ADDED: "该车辆已被登记",
    ERROR_DRIVER_ADDED: "该司机已被登记",
    ERROR_VERIFY_ADDED: "该用户已被认证",
    ERROR_VERIFY_YET: "尚未通过审核",
    ERROR_DEVICE_TOKEN_ADDED: "设备已存在",
    ERROR_BIZ_LIC_ADDED: "该企业已经认证过，请联系管理员{@@}给你添加子账号权限",
    ERROR_WECHAT_MISSED: "微信用户不存在",
    ERROR_BIZ_OCCUPIED: "该手机号已认证为其他企业下的员工，确认有异议，请联系客服，联系方式400-686-6000。",
    ERROR_DEPARTMENT_ADDED: "部门已经添加",
    ERROR_BOOKING_FAILED: "预约提箱失败",
    ERROR_CANCEL_BOOKING: "取消预约失败",
    ERROR_NO_CONTAINER: "没有可预约的箱源",
    ERROR_TYPE_INCORRECT: "只能添加与当前用户身份相符的子账号",
    ERROR_CORE_BIZ_ADDED: "该地区已经订阅",
    ERROR_REQUEST_TOO_FAST: "请求过于频繁",
    ERROR_LOGIN_EXPIRED: "登录信息过期，请重新登录"
};